### ISSUE TITLE
Container is up and running at Azure, but no SMS arrived

### ISSUE THREAD

**Issue by akuryan** [InternetLess/sender#2]
I've created a container at Azure and verified that it is up and running (HTTPS request returns 500 code to me  for route /)
I've sent email to powerfulmachines with a link, but no SMS still :(

**Comment by michaelkotor** [comment]
500 means this is an internal error, that might mean you did something wrong. Also, now there are some limits. Be sure, you the latest version of the app.

**Comment by akuryan** [comment]
Tested with cURL curl https://myApp/ -X POST --data 'p7cGAJmzO0259KNRuUJUVrmH5Fi5r5NUuSSET7kdtEq5jstNmerrUA==' - data arrived to my mobile 
So, seems that email have not reached the target :( or I was not included in distribution list.

**Comment by PowerfulMachine** [comment]
@akuryan Здравствуйте! Мне кажется, я получал ваше письмо и добавлял ваш endpoint в список рассылки. Смс так и не заработали позже?
Если нет, сорри, мы столкнулись с неожиданными техническими сложностями, в итоге приложение работало не очень у большого кол-ва людей. Но многим помогло.
К следующему разу всё поправим :)

**Comment by akuryan** [comment]
У выніку запрацавала - імаверна, першапачаткова эндпоінт не дадаўся, але
потым, калі я наноў пераслаў яго - то я пачаў атрымліваць паведамленні.
