### ISSUE TITLE
Google Cloud Run Service Agent must have permission to read the image, gcr.io/internetless/sender:latest.

### ISSUE THREAD

**Issue by RandomDd** [InternetLess/sender#3]
> Google Cloud Run Service Agent must have permission to read the image, gcr.io/internetless/sender:latest. Ensure that the provided container image URL is correct and that the above account has permission to access the image. If you just enabled the Cloud Run API, the permissions might take a few minutes to propagate. Note that the image is from project [internetless], which is not the same as this project [splendid-light-294302]. Permission must be granted to the Google Cloud Run Service Agent from this project.

Я можа проста тупой, але вось што я атрымоўваю пры спробе развярнуць образ.

**Comment by PowerfulMachine** [comment]
@RandomDd Попробуйте, пожалуйста, образ по новому адресу gcr.io/internetless-sender/sender:latest

**Comment by RandomDd** [comment]
Дзякуй!
